# Generated by Django 2.2.4 on 2019-08-26 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('recipesapp', '0001_initial'), ('recipesapp', '0002_auto_20190819_1720'), ('recipesapp', '0003_auto_20190820_0744'), ('recipesapp', '0004_auto_20190820_0757'), ('recipesapp', '0005_auto_20190820_0800'), ('recipesapp', '0006_auto_20190820_0802'), ('recipesapp', '0007_auto_20190820_0938'), ('recipesapp', '0008_auto_20190820_1404'), ('recipesapp', '0009_auto_20190821_1036')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('procedure', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipesapp.Recipe')),
            ],
        ),
    ]
