# Generated by Django 2.2.4 on 2019-08-19 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='MyRecipe',
        ),
    ]
