# Generated by Django 2.2.4 on 2019-08-20 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0003_auto_20190820_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField()),
                ('name', models.TextField()),
                ('time', models.DurationField()),
                ('serves', models.PositiveSmallIntegerField()),
                ('ingredients', models.TextField()),
                ('procedure', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='MyRecipe',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipesapp.Recipe'),
        ),
    ]
