# Generated by Django 2.2.4 on 2019-08-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0004_auto_20190820_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.TimeField(),
        ),
    ]
