# Generated by Django 2.2.4 on 2019-08-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0006_auto_20190820_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='serves',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='time',
        ),
    ]
