# Generated by Django 2.2.4 on 2019-08-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0008_auto_20190820_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.TextField(),
        ),
    ]
